import Script from "next/script";

export default function Head() {
  return (
    <>
      <title>Kanban</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <Script src="https://kit.fontawesome.com/9e57051f48.js" crossOrigin="anonymous" />
    </>
  );
}
